from osv import fields,osv
import datetime
from base_status.base_stage import base_stage
import tools
from tools.translate import _
from tools import html2plaintext

class under_writer(osv.osv):
    _description = 'underwriter'
    _name = "under.writer"
    _columns = {
            'lender_name':fields.many2one('res.partner','Lender Name'),
            'phone':fields.char('Phone',size=64),
            'email': fields.char('Email', size=240),
            'related_product':fields.many2one('product.product','Related Product'),
            'co-applicants':fields.boolean('Co-Applicants'),
            'guarantors':fields.boolean('Guarantors'),
            'spousal_consent':fields.boolean('Spousal Consent'),
            'spousal_consent':fields.boolean('Spousal Consent'),
            'purchase': fields.char('Purchase', size=240),
            'purchase_plus_improvements': fields.char('Purchase plus improvements', size=240),
            'refinance': fields.char('Refinance', size=240),
            'equity_take_out': fields.char('Equity Take Out', size=240),
            'Switch_Transfer': fields.char('Switch/Transfer', size=240),
            'Port': fields.char('Port', size=240),
            'portability_plus': fields.char('Portability Plus', size=240),
            'line_of_credit': fields.char('Line of Credit', size=240),
            'line_of_credit': fields.char('Line of Credit', size=240),
            'CashBack': fields.char('CashBack', size=240),
            'non_income_qualifier': fields.char('Non-Income Qualifier', size=240),
            'non_resident': fields.char('Non Resident', size=240),
            'blanket_mortgage': fields.char('Blanket Mortgage', size=240),
            'vendor_take_back': fields.char('Vendor Take Back', size=240),
            'charge_on_title': fields.char('Charge on Title', size=240),
            'charge_on_title': fields.char('Charge on Title', size=240),
            '1stmortgage':fields.boolean('1st Mortgage'),
            '2ndmortgage':fields.boolean('2nd Mortgage'),
            '3rdmortgage':fields.boolean('3rd Mortgage'),
            '4thmortgage':fields.boolean('4th Mortgage'),
            '4thmortgage':fields.boolean('4th Mortgage'),
            'bridge':fields.boolean('Bridge'),
            'private_mortgage':fields.boolean('Private Mortgage'),
            'insured':fields.boolean('Insured'),
            'residential':fields.boolean('Residential'),
            'agricultural':fields.boolean('Agricultural'),
            'commercial':fields.boolean('Commercial'),            
            'maximum_acreage_valued ': fields.selection([('10_acres', '10 acres'), ('50_acres', '50 acres'),            
            ('200_acres', '200 acres'),('Unlimited','Unlimited')], 'Maximum Acreage Valued '),
            'condo':fields.integer('Condo'),
                        
            'fractional_interests':fields.boolean('Commercial'),
            'co-operative_housing':fields.boolean('co-operative housing'),    
            'grow_ops':fields.boolean('Grow Ops'),    
            'rental_pools':fields.boolean('Rental Pools'),    
            'life_leased_properties':fields.boolean('life leased properties'),    
            'leased_land':fields.boolean('Leased Land'),    
            'mobile_homes':fields.boolean('mobile homes'),    
            'modular_homes':fields.boolean('modular homes'),    
            'floating_homes':fields.boolean('floating homes'),    
            'boarding_houses':fields.boolean('boarding houses'),    
            'rooming_houses':fields.boolean('rooming houses'),    
            'non_conventional_construction':fields.boolean('non conventional construction'),    
            'age_restricted_properties': fields.selection([('yes', 'yes'), ('no', 'no'),
            ('18', '18+'),('30','30+'),('40','40+'),('50','50+'),('50','50+')], 'Age Restricted Properties'),  
            'house':fields.integer('House'),            
            'minimum_loan_amount':fields.integer('Minimum Loan Amount'),
            'maximum_loan_amount':fields.integer('Maximum Loan Amount'),
            'Bankruptcy': fields.selection([('will_not_consider', 'will not consider'), ('1_month', '1 month'),
                ('2_month', '2 month'),('6_month','6 month'),('2_year','2 year')], 'Bankruptcy'),              
            'allowable_gds':fields.char('allowable gds',size=240),            
            'beacon_tds_split':fields.integer('beacon tds split'),            
            'allowable_tds_below_split':fields.char('allowable tds - below split',size=240),
            'allowable_tds_above_split':fields.char('allowable tds - above split ',size=240),
            
            'High_Ratio_Second_Home':fields.boolean('High Ratio Second Home'),        
            'Cottage_Properties':fields.boolean('Cottage Properties'),
            'Non_Resident_Borrowers':fields.boolean('Non Resident Borrowers'),
            'Non_Permanent_Resident_Borrowers':fields.boolean('Non Permanent Resident Borrowers'),
            'limit':fields.integer('Limit'),
            'stated_income':fields.boolean('Stated Income'),            
            'Accept_Self_Employed':fields.boolean('Accept Self-Employed'),            
            'Power_of_Attorney':fields.boolean('Power of Attorney'),            
            
            
#            'Power_of_Attorney':fields.boolean('Power of Attorney'),            
            'allowable_major_urban_centre':fields.char('allowable major urban centre',size=240),
            'allowable_urban_centre':fields.char('allowable urban centre',size=240),
            'allowable_non_urban_recreational':fields.char('allowable non urban/recreational',size=240),    
            'allowable_small_communities':fields.char('allowable small communities',size=240),    
            'threshold':fields.char('Threshold ',size=240),    
            'below_threshold':fields.char('below threshold',size=240),    
            'above_threshold':fields.char('above threshold ',size=240),    
            'rental_threshold':fields.char('Threshold ',size=240),    
            'below':fields.char('below',size=240),  
            'above':fields.char('above',size=240),  
            'Major_Urban_Centres':fields.char('Major Urban Centres',size=240),  
            'Urban_Centre':fields.char('Urban Centre',size=240),  
            'Non_Urban_Centres':fields.char('Non Urban Centres',size=240),  
            'Small_Communities':fields.char('Small Communities',size=240),  
            'Title_Insurance':fields.boolean('Title Insurance'),            
            'New_Immigrants':fields.boolean('New Immigrants'),            
            'Canadian_Military_Personnel':fields.boolean('Canadian Military Personnel'),            
            'In_House_Registratio_Program':fields.boolean('In House Registration Program'),            
            'currently_renting':fields.boolean('currently renting'),            
            'remove_double_liabilities':fields.boolean('remove double liabilities'),            
            'prepayment_options':fields.boolean('prepayment options'),            
            'company_name':fields.boolean('company name'),            
            'rental_offset':fields.boolean('rental offset'),            
            'last_year_income':fields.boolean('last year income'),            
            'pro_rate_income':fields.boolean('pro rate income'),            
            'open_lines_of_credit':fields.boolean('open lines of credit'),            
            'credit_bureau_liabilities':fields.boolean('credit bureau liabilities'),            
            'combine_Credit_card_debt':fields.boolean('combine Credit card debt'),
            'payment_on_credit_card_loan':fields.boolean('payment on credit card loan'),
            'income_grossed_up':fields.boolean('income grossed up'),
            'bridge_financing':fields.boolean('bridge financing'),                        
    }

under_writer()