{
    "name" : "syml ",
    "version" : "1.0",
    "description":"latest code updated on 12th Dec",
    "author" : "Bista Solutions pvt ",
    "category" : "crm hr",
    "depends" : ["base","crm","hr","hr_recruitment","product","purchase","document","base_calendar","mail"],
    "init_xml" : [],
    'data': [
              'hr_recruitment_stage_data.xml',
              'crm_stage_data.xml',
    ],
    "update_xml" : [		  	
                    'wizard/leads_view.xml',
                    'wizard/applicant_view.xml' ,
#                    'security/syml_security.xml',
                    'morweb.xml',
		    'customer_view.xml',
                    'menu.xml',
                    'crm_lead_view.xml',                   
                    'hr_application_view.xml',
                    'hr_employee_view.xml',
                    'product_view.xml',
                    'opportunity_view.xml',
#                    'crm_cases_view.xml',
                    'document_search_view.xml',
                    'res_users_view.xml',
                    'email_template.xml',
#                    'underwriting_app.xml',
                    #'visdom_website_view.xml',
                    'applicant_record_view.xml',
                    'res_company_view.xml',
		    'product_choice_report.xml',	
                    ],
    "active": False,
    "installable": True
}
